version: '3.5'

services:
  net:
    image: alpine:3.7
    network_mode: bridge
    ports:
      - 2000:2000
    command: tail -f /dev/null
    restart: always
  dev:
    build:
      context: .
      target: dev
    volumes:
      - "$PWD:/data"
    working_dir: /data
    command: tail -f /dev/null
  v350c:
    build:
      context: .
      target: v350c
    network_mode: service:net
    depends_on:
      - db
    env_file:
      - .env
    command: /bin/bash -i ./wait-for-it.sh 127.0.0.1:3306 -- ./ServerStart.sh
  v380c:
    build:
      context: .
      target: v380c
    network_mode: service:net
    depends_on:
      - db
    env_file:
      - .env
    command: /bin/bash -i ./wait-for-it.sh 127.0.0.1:3306 -- ./ServerStart.sh
  db:
    image: mariadb:10
    network_mode: service:net
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin

volumes:
  db-data:
